### ISSUE TITLE
why do you use Redis Pubsub

### ISSUE THREAD

**Issue by MaryLilian** [marcos-demetrio/redis-pubsub#1]
Hi, I am reading your project and I love this project
I have a question, why do you choose Redis Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me it. I am wondering when I should choose Redis Pubsub instead of others like RabbitMQ or Kafka

**Comment by marcos-demetrio** [comment]
Hi @MaryLilian, I was just learning how to use redis pubsub in a simple way, and I also have other projects that use Kafka. ASAP I will create one using rabbitmq.
